version: '2.4'

services:
  crud-pessoa-dev-db:
    image: postgres
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DEV_DB}
    ports:
      - "5433:5432"
    restart: always
    networks:
      - crud-pessoa-network 
   
  crud-pessoa-back-end:
    build:
      dockerfile: ./Dockerfile
      context: ./crud-pessoa-back-end
    image: victorhfsilva/crud-pessoa-back-end
    ports:
      - "8080:8080"
    env_file:
      - ./crud-pessoa-back-end/.env
    depends_on:
      - crud-pessoa-dev-db
    networks:
      - crud-pessoa-network 

networks:
  crud-pessoa-network:
    driver: bridge
